#!/bin/sh

set -x

echo '192.0.220.105    pdr-01' >> /etc/hosts
cp /secrets/portus.crt /usr/local/share/ca-certificates
cp /secrets/portus-CA.crt /usr/local/share/ca-certificates
update-ca-certificates
registry serve /etc/docker/registry/config.yml
