#!/bin/bash

echo '192.0.220.105    pdr-01' >> /etc/hosts
cp /certificates/portus.crt /usr/local/share/ca-certificates
cp /certificates/portus-CA.crt /usr/local/share/ca-certificates
update-ca-certificates

echo "Checking dependencies..."
yarn check &> /dev/null
if [ $? -ne 0 ]; then
  echo "Installing dependencies..."
  yarn install --no-emoji --no-progress
fi

yarn run webpack
