#!/bin/bash

echo '192.0.220.105    pdr-01' >> /etc/hosts
cp /certificates/portus.crt /usr/local/share/ca-certificates
cp /certificates/portus-CA.crt /usr/local/share/ca-certificates
update-ca-certificates

# Wait for mariadb
while true; do
    if bundle exec rake db:migrate:reset; then
        bundle exec rake db:seed
        break
    fi

    echo "Waiting for mariadb to be ready in 5 seconds"
    sleep 5
done

pumactl -F /srv/Portus/config/puma.rb start
